### PR TITLE
fix: missing exports

### PR DESCRIPTION
**Pull request by tanishqmanuja**
Adds two missing exports:
- SendFriendRequest
- RemoveFriendRequest

### CODE REVIEW

**Comment by tanishqmanuja** [comment]
Found one more:
- CurrentGameQuitEndpoint

**Comment by tanishqmanuja** [comment]
For reference if we later decide to write a test

```ts
export async function checkImport(e: ValorantEndpoint) {
  const isImportAvailable = await import("valorant-api-types")
    .then(m => Object.hasOwn(m, e.name))
    .catch(() => false);
  return isImportAvailable;
}
```

**Comment by techchrism** [comment]
Looks good, thank you!
From what I understand of the testing snippet, wouldn't it still require remembering to add the test case?
I might look into using typescript macros or something to add the exports automatically.

**Comment by tanishqmanuja** [comment]
Actually as of the current setup, you have to export a new endpoint both from index.ts and from endpoints.ts. Something one export is missed that is what the test is checking.. if we have exports from both places.

Reference:
https://github.com/tanishqmanuja/valorant-api-client/blob/3710bd8ddfa8eeacf42750d178b173f03041a49e/scripts/endpoints/remote.generator.ts#L28

**Pull request merged**
