### PR TITLE
fix: winsByTier is nullable in MMR

### PR DESCRIPTION
**Pull request by tanishqmanuja**
Sample where parsing failed
```
{
...
       "573f53ac-41a5-3a7d-d9ce-d6a6298e5704": {
          "SeasonID": "573f53ac-41a5-3a7d-d9ce-d6a6298e5704",
          "NumberOfWins": 0,
          "NumberOfWinsWithPlacements": 0,
          "NumberOfGames": 1,
          "Rank": 0,
          "CapstoneWins": 0,
          "LeaderboardRank": 0,
          "CompetitiveTier": 0,
          "RankedRating": 0,
          "WinsByTier": null,
          "GamesNeededForRating": 0,
          "TotalWinsNeededForRank": 0
       },
...
}
```

### CODE REVIEW

**Review by techchrism — APPROVED** [review]
Good catch, thank you

**Comment by techchrism** [comment]
One of the things in the back of my head that I'd like to do is some form of testing with either live requests or just a directory full of saved responses (probably this one). I'd like to make something to anonymize the data though. And the other problem would be that it's difficult to "prove" that a certain output is genuine if a contributor recommends a change. I don't think anybody would lie but it's just nice to be sure haha.

**Comment by techchrism** [comment]
I'll bump the version tomorrow morning

**Comment by tanishqmanuja** [comment]
> I'd like to make something to anonymize the data though.

Live request idea is not too good IMO as your account data may never show the data which others receive on testing. For example => null case of this PR, if you have played all seasons.

Second one is tedious but more reliable because if you somehow manage to write test responses for all endpoints, The scope of a user finding bug before you is very minimal.

**Pull request merged**
